### PR TITLE
Update tutorial to link with setting up commodore alias

### PR DESCRIPTION
**Pull request by ccremer**
Remove the alias defined here, which was not the same as described in https://docs.syn.tools/commodore/running-commodore.html

### CODE REVIEW

**Comment by corvus-ch** [comment]
Sadly this does not work. See https://syn.tools/commodore/running-commodore.html.

**Comment by ccremer** [comment]
ah thanks, didn't see that one.
Also, at least known_hosts has also to be there, as I've found out :)

Should we rather link to this explanation in the tutorial than having to maintain another version of the command alias?

**Comment by corvus-ch** [comment]
Yes, Running Commodore was written to tackle the issue of different and sometimes wrong examples being spread all over the place.

I have updated the example for macOS (commodore/pull/228). Meanwhile I have found halve of a solution.

**Review by corvus-ch — APPROVED** [review]
LGTM

Please note that our style guide states to have only one sentence per line (https://syn.tools/syn/references/style-guide.html#_asciidoc_style).

**Comment by ccremer** [comment]
Hm, the whole tutorial does not adhere to the style guide. Only every paragraph is in its own line, but not sentences. I think I'll stick to the current one for consistency reasons, otherwise I'd have to touch every single paragraph.

**Comment by corvus-ch** [comment]
I mentioned the style guide FYI. Reformatting everything is definitely not what I ask for. I would suggest to do this gradually when touching things anyway. Feel free to leave it as it is for now.

**Pull request merged**
